### Load the data

In [1]:
import pandas as pd

X = pd.read_csv("C:/Projects/03_Advanced_house_price _predictor/data/cleaned/X_features.csv")
y = pd.read_csv("C:/Projects/03_Advanced_house_price _predictor/data/cleaned/y_log_price.csv").squeeze()

### Train-Test Split

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

### Baseline Model : Linear Regression

In [3]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [4]:
# Make Prediction
y_pred_lr = lr.predict(X_test)

In [5]:
# Evaluate the model
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

rmse_lr, r2_lr

(np.float64(0.17754120230374187), 0.8815542258995994)

### Ridge Regression

In [6]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=1.0)
ridge.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)

rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge))
r2_ridge = r2_score(y_test, y_pred_ridge)

rmse_ridge, r2_ridge

c:\Users\shwey\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py:215: LinAlgWarning: Ill-conditioned matrix (rcond=4.86987e-24): result may not be accurate.
  return linalg.solve(A, Xy, assume_a="pos", overwrite_a=True).T

(np.float64(0.17685833653135904), 0.8824636150122033)

### Interpret Coefficients

In [7]:
coef_df = pd.DataFrame({
    "feature": X.columns,
    "coefficient": ridge.coef_
}).sort_values(by="coefficient", key=abs, ascending=False)

coef_df.head(10)

          feature  coefficient
13            lat     1.031587
48  zipcode_98039     0.736083
27  zipcode_98004     0.715196
72  zipcode_98112     0.617870
71  zipcode_98109     0.561967
49  zipcode_98040     0.540170
77  zipcode_98119     0.533203
65  zipcode_98102     0.529383
67  zipcode_98105     0.497467
78  zipcode_98122     0.415412

### Convert predictions back to price

In [8]:
price_pred = np.expm1(y_pred_ridge)

### Random Forest

In [9]:
# Train the random forest
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

RandomForestRegressor(n_estimators=200, n_jobs=-1, random_state=42)

In [10]:
# Predict and evaluate
y_pred_rf = rf.predict(X_test)

rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

rmse_rf, r2_rf

(np.float64(0.16982850800359794), 0.8916216722041103)

In [11]:
# feature Importance (Random Forest)
import pandas as pd

rf_importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf.feature_importances_
}).sort_values(by="importance", ascending=False)

rf_importance.head(10)

          feature  importance
9           grade    0.332034
13            lat    0.305502
3     sqft_living    0.180642
14           long    0.040741
15  sqft_living15    0.022429
4        sqft_lot    0.013613
19      house_age    0.013223
16     sqft_lot15    0.010116
11       yr_built    0.008473
7            view    0.008387

### XGBoost Regressor

In [ ]:
#pip install xgboost

Collecting xgboost
  Downloading xgboost-3.1.3-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\users\shwey\anaconda3\lib\site-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in c:\users\shwey\anaconda3\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.1.3-py3-none-win_amd64.whl (72.0 MB)
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.3/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.8/72.0 MB 1.6 MB/s eta 0:00:45
    --------------------------------------- 1.6/72.0 MB 2.2 MB/s eta 0:00:32
   - -------------------------------------- 2.6/72.0 MB 3.0 MB/s eta 0:00:24
   -- ------------------------------------- 4.5/72.0 MB 4.2 MB/s eta 0:00:17
   --- ------------------------------------ 6.6/72.0 MB 5.7 MB/s eta 0:00:12
   --- ------------------------------------ 6.6/72.0 MB 5.7 MB/s eta 0:00:12
   --- ------------------------------------ 6.6/72.0 MB 5.7 MB/s eta 0:00:12
   --- ------------------------------------ 7.1/72.0 MB 4.0 MB/s eta 0:00:17
   --- ------------------------------------ 7.1/72.0 MB 4.0 MB/s eta 0:00:17
   --- ------------------------------------ 7.1/72.0 MB 4.0 MB/s eta 0:00:17
   ---- ----------------------------------- 7.3/72.0 MB 3.1 MB/s eta 0:00:21
   ---- ----------------------------------- 7.6/72.0 MB 2.9 MB/s eta 0:00:23
   ---- ----------------------------------- 7.9/72.0 MB 2.7 MB/s eta 0:00:24
   ---- ----------------------------------- 7.9/72.0 MB 2.7 MB/s eta 0:00:24
   ---- ----------------------------------- 7.9/72.0 MB 2.7 MB/s eta 0:00:24
   ---- ----------------------------------- 8.1/72.0 MB 2.3 MB/s eta 0:00:29
   ---- ----------------------------------- 8.4/72.0 MB 2.2 MB/s eta 0:00:30
   ---- ----------------------------------- 8.4/72.0 MB 2.2 MB/s eta 0:00:30
   ---- ----------------------------------- 8.4/72.0 MB 2.2 MB/s eta 0:00:30
   ---- ----------------------------------- 8.7/72.0 MB 1.9 MB/s eta 0:00:33
   ---- ----------------------------------- 8.7/72.0 MB 1.9 MB/s eta 0:00:33
   ---- ----------------------------------- 8.9/72.0 MB 1.8 MB/s eta 0:00:35
   ----- ---------------------------------- 9.2/72.0 MB 1.8 MB/s eta 0:00:36
   ----- ---------------------------------- 9.2/72.0 MB 1.8 MB/s eta 0:00:36
   ----- ---------------------------------- 9.2/72.0 MB 1.8 MB/s eta 0:00:36
   ----- ---------------------------------- 9.4/72.0 MB 1.7 MB/s eta 0:00:38
   ----- ---------------------------------- 9.7/72.0 MB 1.6 MB/s eta 0:00:39
   ----- ---------------------------------- 9.7/72.0 MB 1.6 MB/s eta 0:00:39
   ----- ---------------------------------- 10.0/72.0 MB 1.6 MB/s eta 0:00:40
   ----- ---------------------------------- 10.2/72.0 MB 1.6 MB/s eta 0:00:40
   ----- ---------------------------------- 10.5/72.0 MB 1.5 MB/s eta 0:00:41
   ----- ---------------------------------- 10.5/72.0 MB 1.5 MB/s eta 0:00:41
   ----- ---------------------------------- 10.5/72.0 MB 1.5 MB/s eta 0:00:41
   ----- ---------------------------------- 10.7/72.0 MB 1.5 MB/s eta 0:00:43
   ----- ---------------------------------- 10.7/72.0 MB 1.5 MB/s eta 0:00:43
   ------ --------------------------------- 11.0/72.0 MB 1.4 MB/s eta 0:00:43
   ------ --------------------------------- 11.0/72.0 MB 1.4 MB/s eta 0:00:43
   ------ --------------------------------- 11.3/72.0 MB 1.3 MB/s eta 0:00:46
   ------ --------------------------------- 11.3/72.0 MB 1.3 MB/s eta 0:00:46
   ------ --------------------------------- 11.5/72.0 MB 1.3 MB/s eta 0:00:46
   ------ --------------------------------- 11.5/72.0 MB 1.3 MB/s eta 0:00:46
   ------ --------------------------------- 11.5/72.0 MB 1.3 MB/s eta 0:00:46
   ------ --------------------------------- 11.8/72.0 MB 1.3 MB/s eta 0:00:48
   ------ --------------------------------- 12.1/72.0 MB 1.3 MB/s eta 0:00:48
   ------ --------------------------------- 12.1/72.0 MB 1.3 MB/s eta 0:00:48
   ------ --------------------------------- 12.1/72.0 MB 1.3 MB/s eta 0:00:48
   ------ --------------------------------- 12.3/72.0 MB 1.2 MB/s eta 0:00:50
   ------ --------------------------------- 12.3/72.0 MB 1.2 MB/s eta 0:00:50
   ------ --------------------------------- 12.6/72.0 MB 1.2 MB/s eta 0:00:50
   ------ --------------------------------- 12.6/72.0 MB 1.2 MB/s eta 0:00:50
   ------ --------------------------------- 12.6/72.0 MB 1.2 MB/s eta 0:00:50
   ------- -------------------------------- 12.8/72.0 MB 1.2 MB/s eta 0:00:52
   ------- -------------------------------- 12.8/72.0 MB 1.2 MB/s eta 0:00:52
   ------- -------------------------------- 12.8/72.0 MB 1.2 MB/s eta 0:00:52
   ------- -------------------------------- 13.1/72.0 MB 1.1 MB/s eta 0:00:53
   ------- -------------------------------- 13.4/72.0 MB 1.1 MB/s eta 0:00:54
   ------- -------------------------------- 13.4/72.0 MB 1.1 MB/s eta 0:00:54
   ------- -------------------------------- 13.4/72.0 MB 1.1 MB/s eta 0:00:54
   ------- -------------------------------- 13.6/72.0 MB 1.1 MB/s eta 0:00:55
   -------- ------------------------------- 16.0/72.0 MB 1.2 MB/s eta 0:00:46
   --------- ------------------------------ 17.6/72.0 MB 1.3 MB/s eta 0:00:41
   --------- ------------------------------ 17.8/72.0 MB 1.3 MB/s eta 0:00:41
   --------- ------------------------------ 17.8/72.0 MB 1.3 MB/s eta 0:00:41
   ---------- ----------------------------- 18.6/72.0 MB 1.4 MB/s eta 0:00:40
   ---------- ----------------------------- 18.6/72.0 MB 1.4 MB/s eta 0:00:40
   ---------- ----------------------------- 18.6/72.0 MB 1.4 MB/s eta 0:00:40
   ---------- ----------------------------- 19.4/72.0 MB 1.4 MB/s eta 0:00:39
   ----------- ---------------------------- 19.9/72.0 MB 1.4 MB/s eta 0:00:39
   ----------- ---------------------------- 19.9/72.0 MB 1.4 MB/s eta 0:00:39
   ----------- ---------------------------- 20.2/72.0 MB 1.4 MB/s eta 0:00:39
   ----------- ---------------------------- 20.7/72.0 MB 1.4 MB/s eta 0:00:38
   ----------- ---------------------------- 21.0/72.0 MB 1.4 MB/s eta 0:00:38
   ----------- ---------------------------- 21.0/72.0 MB 1.4 MB/s eta 0:00:38
   ----------- ---------------------------- 21.2/72.0 MB 1.3 MB/s eta 0:00:38
   ------------ --------------------------- 21.8/72.0 MB 1.4 MB/s eta 0:00:37
   ------------ --------------------------- 22.0/72.0 MB 1.4 MB/s eta 0:00:37
   ------------ --------------------------- 22.0/72.0 MB 1.4 MB/s eta 0:00:37
   ------------ --------------------------- 22.5/72.0 MB 1.4 MB/s eta 0:00:37
   ------------ --------------------------- 22.5/72.0 MB 1.4 MB/s eta 0:00:37
   ------------ --------------------------- 22.8/72.0 MB 1.3 MB/s eta 0:00:37
   -------------- ------------------------- 26.0/72.0 MB 1.5 MB/s eta 0:00:31
   --------------- ------------------------ 27.5/72.0 MB 1.6 MB/s eta 0:00:29
   --------------- ------------------------ 27.5/72.0 MB 1.6 MB/s eta 0:00:29
   --------------- ------------------------ 27.5/72.0 MB 1.6 MB/s eta 0:00:29
   --------------- ------------------------ 28.0/72.0 MB 1.6 MB/s eta 0:00:29
   --------------- ------------------------ 28.3/72.0 MB 1.5 MB/s eta 0:00:29
   --------------- ------------------------ 28.6/72.0 MB 1.5 MB/s eta 0:00:29
   ---------------- ----------------------- 28.8/72.0 MB 1.5 MB/s eta 0:00:29
   ---------------- ----------------------- 29.4/72.0 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 29.4/72.0 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 29.6/72.0 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 29.9/72.0 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 29.9/72.0 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 30.1/72.0 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 30.1/72.0 MB 1.5 MB/s eta 0:00:28
   ---------------- ----------------------- 30.4/72.0 MB 1.5 MB/s eta 0:00:28
   ----------------- ---------------------- 30.7/72.0 MB 1.5 MB/s eta 0:00:28
   ----------------- ---------------------- 30.7/72.0 MB 1.5 MB/s eta 0:00:28
   ----------------- ---------------------- 30.9/72.0 MB 1.5 MB/s eta 0:00:29
   ----------------- ---------------------- 30.9/72.0 MB 1.5 MB/s eta 0:00:29
   ----------------- ---------------------- 31.2/72.0 MB 1.5 MB/s eta 0:00:29
   ----------------- ---------------------- 32.0/72.0 MB 1.5 MB/s eta 0:00:28
   ------------------ --------------------- 33.8/72.0 MB 1.5 MB/s eta 0:00:25
   -------------------- ------------------- 36.2/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 36.7/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 36.7/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 37.2/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 37.2/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 37.2/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 37.5/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 37.7/72.0 MB 1.6 MB/s eta 0:00:22
   -------------------- ------------------- 37.7/72.0 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 38.0/72.0 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 38.0/72.0 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 38.3/72.0 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 38.3/72.0 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 38.5/72.0 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 38.5/72.0 MB 1.6 MB/s eta 0:00:22
   --------------------- ------------------ 38.8/72.0 MB 1.5 MB/s eta 0:00:22
   --------------------- ------------------ 38.8/72.0 MB 1.5 MB/s eta 0:00:22
   --------------------- ------------------ 39.1/72.0 MB 1.5 MB/s eta 0:00:22
   --------------------- ------------------ 39.3/72.0 MB 1.5 MB/s eta 0:00:22
   --------------------- ------------------ 39.3/72.0 MB 1.5 MB/s eta 0:00:22
   --------------------- ------------------ 39.3/72.0 MB 1.5 MB/s eta 0:00:22
   ---------------------- ----------------- 41.2/72.0 MB 1.5 MB/s eta 0:00:20
   ----------------------- ---------------- 42.7/72.0 MB 1.6 MB/s eta 0:00:19
   ------------------------ --------------- 44.3/72.0 MB 1.6 MB/s eta 0:00:17
   ------------------------- -------------- 45.6/72.0 MB 1.7 MB/s eta 0:00:16
   ------------------------- -------------- 46.1/72.0 MB 1.7 MB/s eta 0:00:16
   ------------------------- -------------- 46.4/72.0 MB 1.7 MB/s eta 0:00:16
   ------------------------- -------------- 46.7/72.0 MB 1.7 MB/s eta 0:00:16
   ------------------------- -------------- 46.7/72.0 MB 1.7 MB/s eta 0:00:16
   -------------------------- ------------- 46.9/72.0 MB 1.7 MB/s eta 0:00:16
   -------------------------- ------------- 47.2/72.0 MB 1.7 MB/s eta 0:00:15
   -------------------------- ------------- 47.2/72.0 MB 1.7 MB/s eta 0:00:15
   -------------------------- ------------- 47.2/72.0 MB 1.7 MB/s eta 0:00:15
   -------------------------- ------------- 47.4/72.0 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 47.7/72.0 MB 1.6 MB/s eta 0:00:15
   -------------------------- ------------- 47.7/72.0 MB 1.6 MB/s eta 0:00:15
   -------------------------- ------------- 47.7/72.0 MB 1.6 MB/s eta 0:00:15
   -------------------------- ------------- 48.0/72.0 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 48.0/72.0 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 48.0/72.0 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 48.2/72.0 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 48.2/72.0 MB 1.6 MB/s eta 0:00:16
   --------------------------- ------------ 49.5/72.0 MB 1.6 MB/s eta 0:00:15
   --------------------------- ------------ 50.3/72.0 MB 1.5 MB/s eta 0:00:15
   ---------------------------- ----------- 51.6/72.0 MB 1.5 MB/s eta 0:00:14
   ----------------------------- ---------- 52.7/72.0 MB 1.5 MB/s eta 0:00:13
   ----------------------------- ---------- 54.0/72.0 MB 1.6 MB/s eta 0:00:12
   ------------------------------ --------- 55.3/72.0 MB 1.6 MB/s eta 0:00:11
   ------------------------------- -------- 56.4/72.0 MB 1.6 MB/s eta 0:00:10
   -------------------------------- ------- 57.7/72.0 MB 1.7 MB/s eta 0:00:09
   -------------------------------- ------- 59.0/72.0 MB 1.7 MB/s eta 0:00:08
   -------------------------------- ------- 59.2/72.0 MB 1.7 MB/s eta 0:00:08
   --------------------------------- ------ 59.8/72.0 MB 1.8 MB/s eta 0:00:07
   --------------------------------- ------ 59.8/72.0 MB 1.8 MB/s eta 0:00:07
   --------------------------------- ------ 60.0/72.0 MB 1.7 MB/s eta 0:00:07
   --------------------------------- ------ 60.3/72.0 MB 1.7 MB/s eta 0:00:07
   --------------------------------- ------ 60.8/72.0 MB 1.8 MB/s eta 0:00:07
   --------------------------------- ------ 61.1/72.0 MB 1.8 MB/s eta 0:00:07
   ---------------------------------- ----- 61.9/72.0 MB 1.8 MB/s eta 0:00:06
   ---------------------------------- ----- 62.4/72.0 MB 1.8 MB/s eta 0:00:06
   ----------------------------------- ---- 63.4/72.0 MB 1.8 MB/s eta 0:00:05
   ----------------------------------- ---- 64.2/72.0 MB 1.8 MB/s eta 0:00:05
   ------------------------------------ --- 65.3/72.0 MB 1.9 MB/s eta 0:00:04
   ------------------------------------ --- 66.3/72.0 MB 1.9 MB/s eta 0:00:03
   ------------------------------------- -- 67.1/72.0 MB 1.9 MB/s eta 0:00:03
   ------------------------------------- -- 68.2/72.0 MB 2.0 MB/s eta 0:00:02
   -------------------------------------- - 69.2/72.0 MB 2.0 MB/s eta 0:00:02
   ---------------------------------------  70.3/72.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  71.3/72.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  71.8/72.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 72.0/72.0 MB 2.1 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.1.3
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# Train the XGBoost
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.8, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

In [15]:
# Predict and Evaluate
y_pred_xgb = xgb.predict(X_test)

rmse_xgb = np.sqrt(mean_squared_error(y_test, y_pred_xgb))
r2_xgb = r2_score(y_test, y_pred_xgb)

rmse_xgb, r2_xgb

(np.float64(0.15162970009300195), 0.9136047611925715)

## Model Comparison Table

In [16]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Ridge Regression", "Random Forest", "XGBoost"],
    "RMSE (log)": [rmse_lr, rmse_ridge, rmse_rf, rmse_xgb],
    "R2": [r2_lr, r2_ridge, r2_rf, r2_xgb]
})

results

               Model  RMSE (log)        R2
0  Linear Regression    0.177541  0.881554
1   Ridge Regression    0.176858  0.882464
2      Random Forest    0.169829  0.891622
3            XGBoost    0.151630  0.913605

lowest RMSE and highest R2 is the best model so XGBoost is the best model for this project.

## Convert best model predictions to price

In [17]:
price_pred_xgb = np.expm1(y_pred_xgb)
price_true = np.expm1(y_test)